function mountFeedbackCoach(root, options = {}) {
  root.classList.add('fc-root');
  const signedUserEl=document.getElementById('signedUser'); if(signedUserEl) signedUserEl.textContent=options.userName||'Usuario de Teams';
  if (options.isTeams) root.dataset.teams = 'true';
  if (options.frameContext) root.dataset.teamsContext = options.frameContext;
  if (options.meetingId) root.dataset.meetingId = options.meetingId;

  const KEY='feedback_coach_ai_final_v4';
  const FEEDBACK_API='https://axet.nttdata.com/flows/cloud/27153-v2/feedback-coach/live';
  const NAV=[
   ['dashboard','◆','Dashboard'],['live','●','Sesión en vivo','IA'],['feedback','✎','Feedback'],['om','◔','Oportunidades de Mejora'],['challenges','▣','Desafíos'],['follow','↻','Seguimiento Advisor'],['people','☰','Directorio'],['settings','⚙','Configuración']
  ];
  const TITLES={dashboard:['Dashboard','Visión ejecutiva del ciclo de feedback y desarrollo'],live:['Sesión en vivo','El coach analiza la conversación registrada y recomienda la mejor siguiente pregunta'],feedback:['Feedback','Registros estructurados y sujetos a revisión humana'],om:['Oportunidades de Mejora','Brechas trazables en formato Situación · Comportamiento · Impacto'],challenges:['Desafíos','Feed-forward convertido en compromisos medibles'],follow:['Seguimiento Advisor','Cierre de loop después de cada feedback'],people:['Directorio','Maestro de personas, cliente, equipo y Advisor'],settings:['Configuración','Métricas, cobertura y reglas del coach']};
  const DIMS=[['context','Contexto'],['strength','Fortalezas'],['positiveEvidence','Evidencia positiva'],['om','OM'],['situation','Situación'],['behavior','Comportamiento'],['impact','Impacto'],['frequency','Frecuencia'],['expectation','Expectativa'],['challenge','Desafío'],['success','Criterio éxito'],['satisfaction','Satisfacción'],['recommend','Recomendación'],['metricsWhy','Motivo métricas']];
  const seed=()=>({
   seq:{p:0,f:0,o:0,c:0,m:0,a:0},
   people:[], feedback:[], oms:[], challenges:[], meetings:[], audit:[],
   config:{sessionMinutes:30,coverageTarget:75,questionMode:'private',metricScale:10}
  });
  function days(n){const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
  let db;try{db=JSON.parse(localStorage.getItem(KEY))||seed()}catch(e){db=seed()}
  let state={view:'dashboard',session:null};
  const $=s=>root.querySelector(s); const $$=s=>Array.from(root.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function persist(){localStorage.setItem(KEY,JSON.stringify(db))}
  function person(id){return db.people.find(x=>String(x.id)===String(id))}
  function fmt(d){if(!d)return '—';const [y,m,dd]=d.split('-');return `${dd}/${m}/${y}`}
  function id(k){db.seq[k]=(db.seq[k]||0)+1;return db.seq[k]}
  function nav(){ $('#nav').innerHTML=NAV.map(n=>`<button data-v="${n[0]}" class="${state.view===n[0]?'active':''}"><span>${n[1]}</span>${n[2]}${n[3]?`<span class="tag">${n[3]}</span>`:''}</button>`).join(''); $$('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;render()}) }
  function render(){nav();const t=TITLES[state.view];$('#title').textContent=t[0];$('#subtitle').textContent=t[1];({dashboard:renderDashboard,live:renderLive,feedback:renderFeedback,om:renderOM,challenges:renderChallenges,follow:renderFollow,people:renderPeople,settings:renderSettings}[state.view]||renderDashboard)()}
  function renderDashboard(){
   const openOM=db.oms.filter(o=>!['6-Superado','7-Archivado'].includes(o.state)).length;
   const inProg=db.challenges.filter(c=>c.state==='En progreso').length;
   const overdue=db.challenges.filter(c=>c.due<days(0)&&c.state!=='Hecho').length;
   const pending=db.meetings.filter(m=>!m.done).length;
   const view=$('#view'); view.innerHTML=`
   <div class="grid g4">
    ${kpi('Feedbacks',db.feedback.length,'registros totales')}${kpi('OM abiertas',openOM,'brechas en desarrollo')}${kpi('Desafíos activos',inProg,'en ejecución')}${kpi('Seguimientos',pending,'reuniones Advisor pendientes')}
   </div>
   <div class="grid g2" style="margin-top:16px">
    <div class="card"><h3>Casos que requieren atención</h3><div class="rank">${db.feedback.slice().sort((a,b)=>(a.sat+a.rec)-(b.sat+b.rec)).slice(0,5).map((f,i)=>`<div class="rankItem"><div class="n">${i+1}</div><div class="grow"><b>${esc(person(f.personId)?.name)}</b><small>${esc(f.client)} · ${fmt(f.date)}</small></div><span class="badge ${f.sat<=6?'bad':'warn'}">${f.sat}/10</span></div>`).join('')||'<div class="empty">Sin feedback todavía.</div>'}</div></div>
    <div class="card"><h3>Próximos pasos</h3><div class="rank">${db.meetings.filter(m=>!m.done).map((m,i)=>`<div class="rankItem"><div class="n">↻</div><div class="grow"><b>${esc(person(m.personId)?.name)}</b><small>Advisor: ${esc(m.advisor)} · ${fmt(m.date)}</small></div><span class="badge agentb">Pendiente</span></div>`).join('')||'<div class="empty">No hay seguimientos pendientes.</div>'}</div></div>
   </div>
   <div class="card" style="margin-top:16px"><div class="toolbar"><div><h3 style="margin:0">Ciclo de feedback</h3><span class="muted mini">Acompaña la conversación, estructura evidencias y cierra el seguimiento.</span></div><div class="spacer"></div><button class="btn agent" id="goLive">▶ Iniciar sesión</button></div>
   <div class="grid g4">${miniStep('1','Escuchar','Transcripción viva')}${miniStep('2','Desafiar','Next Best Question')}${miniStep('3','Estructurar','Feedback + SBI + métricas')}${miniStep('4','Cerrar loop','Advisor + desafío')}</div></div>`;
   $('#goLive').onclick=()=>{state.view='live';render()}
  }
  function kpi(l,v,f){return `<div class="card kpi"><div class="label">${l}</div><div class="value">${v}</div><div class="foot">${f}</div></div>`}
  function miniStep(n,t,d){return `<div style="padding:10px 0"><span class="badge agentb">${n}</span><div style="font-weight:800;margin-top:7px">${t}</div><div class="muted mini">${d}</div></div>`}
  function renderLive(){ if(!state.session) return renderSetup(); if(state.session.closed) return renderResult(); return renderSession(); }
  function renderSetup(){
   if(!db.people.length){
    $('#view').innerHTML=`<div class="card"><span class="pill">Feedback Coach</span><h3 style="font-size:22px;margin-top:14px">Configura el directorio</h3><p class="muted">Para iniciar una sesión debes registrar primero a la persona evaluada y su Advisor. Esto mantiene trazabilidad entre Feedback, Oportunidades de Mejora, Desafíos y Seguimiento.</p><button class="btn agent" id="goPeople" style="margin-top:8px">Ir al Directorio</button></div>`;
    $('#goPeople').onclick=()=>{state.view='people';render()};
    return;
   }
   const facilitator=options.userName||'';
   $('#view').innerHTML=`<div class="grid g2"><div class="card"><span class="pill">Feedback Coach</span><h3 style="font-size:22px;margin-top:14px">Preparar sesión</h3><p class="muted">Selecciona a la persona evaluada y registra las intervenciones relevantes de la conversación. El coach analizará la cobertura, propondrá preguntas y estructurará el resultado para revisión humana.</p>
   <div class="formgrid" style="margin-top:18px">
   <label class="field wide"><span>Talento evaluado</span><select id="sp"><option value="">Selecciona…</option>${db.people.map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(p.client||'Sin cliente')}</option>`).join('')}</select></label>
   <label class="field"><span>Cliente</span><input id="sc" placeholder="Cliente"></label><label class="field"><span>Duración objetivo</span><input id="sd" type="number" min="10" max="90" value="${db.config.sessionMinutes}"></label>
   <label class="field"><span>Facilitador NTT DATA</span><input id="sf" value="${esc(facilitator)}" placeholder="Nombre del facilitador"></label><label class="field"><span>Rol NTT DATA</span><input id="sfr" placeholder="Ej. Líder de Servicio"></label>
   <label class="field"><span>Contraparte cliente</span><input id="ss" placeholder="Nombre de la contraparte"></label><label class="field"><span>Rol contraparte</span><input id="ssr" placeholder="Ej. Product Owner"></label>
   </div><div class="toolbar" style="margin-top:16px"><button class="btn agent" id="start">▶ Iniciar sesión</button></div></div>
   <div class="card"><h3>Flujo de la sesión</h3><div class="reviewItem"><b>1. Registrar evidencia</b><div class="muted mini">Captura las intervenciones relevantes de la conversación.</div></div><div class="reviewItem"><b>2. Evaluar cobertura</b><div class="muted mini">Identifica qué ya está sustentado y qué información falta.</div></div><div class="reviewItem"><b>3. Recomendar la siguiente pregunta</b><div class="muted mini">Prioriza una sola pregunta útil para profundizar.</div></div><div class="reviewItem"><b>4. Estructurar y aprobar</b><div class="muted mini">Genera reconocimiento, OM-SBI, desafío, métricas y seguimiento con revisión humana.</div></div><div class="notice">La lectura automática de la transcripción nativa de Teams requiere habilitación de Microsoft Graph y un backend corporativo autorizado. Esta versión no afirma capturar audio o transcripción automáticamente.</div></div></div>`;
   $('#sp').onchange=e=>{const p=person(e.target.value); if(p)$('#sc').value=p.client||''};
   $('#start').onclick=()=>{const pid=$('#sp').value;if(!pid){alert('Selecciona a la persona evaluada.');return}const p=person(pid);const source=$('#ss').value.trim();if(!source){alert('Ingresa la contraparte que brinda el feedback.');return}state.session=newSession({personId:+pid,client:$('#sc').value.trim()||p?.client||'',duration:+$('#sd').value||30,fac:$('#sf').value.trim(),facRole:$('#sfr').value.trim(),source:source,sourceRole:$('#ssr').value.trim()});render();};
  }
  function makeApiSessionId(){return `fc-web-${Date.now()}-${Math.random().toString(36).slice(2,10)}`}
  function newSession(c){return {cfg:c,started:Date.now(),apiSessionId:makeApiSessionId(),transcript:[],coverage:Object.fromEntries(DIMS.map(d=>[d[0],'missing'])),facts:{strengths:[],positive:[],om:[],situation:[],behavior:[],impact:[],frequency:[],expectation:[],challenge:[],success:[],metricsWhy:[]},metrics:{sat:null,rec:null,collab:null,performance:null,proactivity:null,valueFeedback:null},qAlt:0,agent:{status:'idle',error:null,data:null,lastAt:null},closed:false,approved:false,result:null}}
  function addLine(who,text){const s=state.session;s.transcript.push({who,text,at:new Date().toISOString()});if(who==='client')analyze(text)}
  function itemText(v){if(v==null)return '';if(typeof v==='string')return v;if(typeof v==='number'||typeof v==='boolean')return String(v);return v.text||v.title||v.evidence||v.description||v.commitment||JSON.stringify(v)}
  function evidenceByType(agent,type){const list=Array.isArray(agent?.evidence)?agent.evidence:[];const match=[...list].reverse().find(e=>String(e?.type||'').toLowerCase()===type);return match?itemText(match):''}
  function syncAgentCoverage(agent){if(!agent)return;const ev=Array.isArray(agent.evidence)?agent.evidence:[];const strengths=Array.isArray(agent.strengths)?agent.strengths:[];const oms=Array.isArray(agent.improvementOpportunities)?agent.improvementOpportunities:[];const challenges=Array.isArray(agent.challenges)?agent.challenges:[];const commitments=Array.isArray(agent.commitments)?agent.commitments:[];if(ev.length||strengths.length||oms.length)mark('context','partial');if(strengths.length)mark('strength');if(strengths.length&&ev.length)mark('positiveEvidence','partial');if(oms.length)mark('om');if(evidenceByType(agent,'situation'))mark('situation');if(evidenceByType(agent,'behavior'))mark('behavior');if(evidenceByType(agent,'impact'))mark('impact');if(agent.suggestedChallenge||challenges.length)mark('challenge');if(commitments.length){mark('expectation');mark('success','partial')}if(agent.readyToClose){mark('expectation');mark('challenge');mark('success')}}
  async function sendFeedbackFragment(text){const s=state.session;if(!s)return null;s.agent.status='loading';s.agent.error=null;s.agent.lastAt=new Date().toISOString();renderSession();try{const response=await fetch(FEEDBACK_API,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({sessionId:s.apiSessionId,speaker:'feedback_provider',text,timestamp:new Date().toISOString()})});if(!response.ok)throw new Error(`Feedback API HTTP ${response.status}`);const data=await response.json();s.agent.data=data;s.agent.status='ready';s.agent.error=null;syncAgentCoverage(data);return data}catch(err){s.agent.status='error';s.agent.error=err&&err.message?err.message:String(err);console.error('Feedback Coach Agentic API error',err);return null}finally{renderSession()}}
  function mark(k,status='complete'){const c=state.session.coverage;const rank={missing:0,partial:1,complete:2};if(rank[status]>rank[c[k]])c[k]=status}
  function has(text,arr){const t=text.toLowerCase();return arr.some(w=>t.includes(w))}
  function pushFact(k,text){const a=state.session.facts[k];if(!a.includes(text))a.push(text)}
  function analyze(text){const t=text.toLowerCase(); const n=(t.match(/\b10\b|\b[1-9]\b/g)||[]).map(Number);
   mark('context','partial');
   if(has(t,['bien','destac','logr','fortaleza','excelente','lider','ownership','valor'])){mark('strength');pushFact('strengths',text)}
   if(has(t,['semana pasada','último sprint','ultimo sprint','ayer','cuando ','en producción','en produccion','durante','en la reunión','en la reunion'])){mark('situation');mark('context');pushFact('situation',text)}
   if(has(t,['coordin','comunic','tomó','tomo','hizo','dejó','dejo','resolv','organizó','organizo','asum','mantuvo','levant'])){mark('behavior');pushFact('behavior',text)}
   if(has(t,['permitió','permitio','generó','genero','provocó','provoco','impact','evitó','evito','retras','tensión','tension','margen','resultado'])){mark('impact');pushFact('impact',text)}
   if(state.session.coverage.strength==='complete'&&state.session.coverage.situation==='complete'&&state.session.coverage.behavior==='complete'&&state.session.coverage.impact==='complete'){mark('positiveEvidence');pushFact('positive',text)}
   if(has(t,['oportunidad','mejorar','mejora','debería','deberia','le falta','necesita','demasiado tarde','tarde','no cumpl'])){mark('om');pushFact('om',text)}
   if(has(t,['a veces','siempre','frecuent','varias veces','una vez','esporád','esporad'])){mark('frequency');pushFact('frequency',text)}
   if(has(t,['me gustaría','me gustaria','esperaría','esperaria','debería','deberia','necesito que','que lo comunique','la próxima','la proxima'])){mark('expectation');pushFact('expectation',text)}
   if(has(t,['desafío','desafio','reto','objetivo','como desafío','como desafio','podría','podria'])){mark('challenge');pushFact('challenge',text)}
   if(has(t,['estaría cumplido','estaria cumplido','sabremos','durante un mes','durante 4','%','criterio','sin riesgos','cada semana'])){mark('success');pushFact('success',text)}
   const sat=t.match(/satisfacci[oó]n[^0-9]{0,20}(10|[1-9])/); const rec=t.match(/recomendaci[oó]n[^0-9]{0,20}(10|[1-9])/);
   if(sat){state.session.metrics.sat=+sat[1];mark('satisfaction')} else if(has(t,['satisfacción','satisfaccion'])&&n.length){state.session.metrics.sat=n[0];mark('satisfaction')}
   if(rec){state.session.metrics.rec=+rec[1];mark('recommend')} else if(has(t,['recomendación','recomendacion','recomendar'])&&n.length){state.session.metrics.rec=n[n.length-1];mark('recommend')}
   if((state.session.metrics.sat||state.session.metrics.rec)&&has(t,['porque','por que','ya que','solo necesita','debido'])){mark('metricsWhy');pushFact('metricsWhy',text)}
  }
  function covPct(){const vals=Object.values(state.session.coverage);return Math.round(vals.reduce((a,v)=>a+(v==='complete'?1:v==='partial'?.5:0),0)/vals.length*100)}
  function nextQuestion(){const s=state.session,p=person(s.cfg.personId),name=p?p.name.split(' ')[0]:'la persona';const a=s.agent&&s.agent.data;if(a){if(a.readyToClose)return {reason:'El agente considera que ya hay evidencia y compromiso suficientes para cerrar.',dim:'Cierre',question:'',agent:true};if(a.nextBestQuestion)return {reason:(Array.isArray(a.missingInformation)&&a.missingInformation.length)?itemText(a.missingInformation[0]):`Fase Agentic: ${a.phase||'análisis'}`,dim:'Agentic AI',question:a.nextBestQuestion,agent:true};}
   const c=s.coverage; const q=(reason,dim,arr)=>({reason,dim,question:arr[s.qAlt%arr.length],agent:false});
   if(!s.transcript.length)return q('Abrir la conversación de forma amplia','Contexto',[`¿Qué ha sido lo más relevante de ${name} en las últimas 3 semanas?`,`Si tuvieras que resumir el periodo reciente de ${name}, ¿qué destacarías primero?`]);
   if(c.strength==='missing')return q('Todavía no hay una fortaleza o reconocimiento sustentado','Fortalezas',[`¿Qué destacarías como logro o fortaleza de ${name} en este periodo?`,`¿Qué comportamiento de ${name} te gustaría que mantenga porque está aportando valor?`]);
   if(c.strength==='complete'&&c.positiveEvidence==='missing')return q('La fortaleza está expresada, pero falta evidencia concreta','Evidencia positiva',[`¿Qué situación reciente demuestra esa fortaleza y qué impacto positivo tuvo?`,`¿Puedes darme un ejemplo concreto de cuándo viste ese comportamiento?`]);
   if(c.om==='missing')return q('Aún no apareció una oportunidad de desarrollo','Oportunidad de Mejora',[`Si tuvieras que elegir una sola cosa que ${name} podría potenciar en las próximas semanas, ¿cuál sería?`,`¿Hay algo que hoy limite el impacto de ${name} y que valga la pena trabajar?`]);
   if(c.situation==='missing')return q('Hay una mejora mencionada, pero falta una situación concreta','Situación',[`¿Puedes contarme una situación específica en la que hayas observado eso?`,`¿Cuándo ocurrió por última vez? Cuéntame ese caso puntual.`]);
   if(c.behavior==='missing')return q('Falta separar percepción de comportamiento observable','Comportamiento',[`¿Qué hizo o dejó de hacer exactamente en esa situación?`,`¿Qué comportamiento concreto observaste, sin interpretarlo?`]);
   if(c.impact==='missing')return q('La situación y el comportamiento están claros; falta el impacto','Impacto',[`¿Qué impacto tuvo eso en el equipo, el cliente o el resultado?`,`¿Qué consecuencia concreta generó ese comportamiento?`]);
   if(c.frequency==='missing')return q('Necesitamos saber si es un caso aislado o un patrón','Frecuencia',[`¿Esto ocurrió una sola vez o lo has visto repetirse?`,`¿Con qué frecuencia dirías que ocurre?`]);
   if(c.expectation==='missing')return q('La brecha está clara, pero no la expectativa futura','Expectativa',[`¿Qué esperarías que hiciera diferente la próxima vez?`,`¿Cómo se vería el comportamiento esperado en la práctica?`]);
   if(c.challenge==='missing')return q('La oportunidad puede convertirse en feed-forward accionable','Desafío',[`¿Quieres plantear esa expectativa como un desafío concreto para ${name}?`,`¿Qué reto específico ayudaría a convertir esta mejora en una acción observable?`]);
   if(c.success==='missing')return q('Hay un desafío, pero todavía no es medible','Criterio de éxito',[`¿Qué significaría para ti que ese desafío se completó?`,`¿Qué evidencia te permitiría decir “esto ya mejoró”?`]);
   if(c.satisfaction==='missing')return q('Falta la señal cuantitativa de satisfacción','Satisfacción',[`Del 1 al 10, ¿qué tan satisfecho estás con el servicio de ${name}?`,`Si tuvieras que poner una nota de satisfacción del 1 al 10, ¿cuál sería?`]);
   if(c.recommend==='missing')return q('Falta la señal de recomendación','Recomendación',[`Del 1 al 10, ¿qué tan probable es que recomiendes a ${name} para un servicio similar?`,`¿Qué nota del 1 al 10 le darías en recomendación?`]);
   if(c.metricsWhy==='missing')return q('Tenemos la puntuación, pero no la explicación','Motivo de métricas',[`¿Por qué elegiste esas puntuaciones? ¿Qué tendría que pasar para subir un punto?`,`¿Qué explica principalmente esas notas?`]);
   return q('La cobertura mínima está completa','Cierre',[`Antes de cerrar, ¿hay algo importante sobre ${name} que no te haya preguntado?`,`Si ${name} leyera una sola idea de esta conversación, ¿cuál debería ser?`]);
  }
  function renderSession(){
   const s=state.session,p=person(s.cfg.personId),q=nextQuestion(),pct=covPct(),mins=Math.floor((Date.now()-s.started)/60000),timepct=Math.min(100,Math.round(mins/s.cfg.duration*100));
   const a=s.agent?.data;const phase=a?.phase||'esperando';const confidence=a&&Number.isFinite(+a.confidence)?Math.round(+a.confidence*100):null;const agentLabel=s.agent?.status==='loading'?'Analizando con Agentic AI…':s.agent?.status==='error'?'Agentic AI no disponible':a?`Agentic AI · ${phase}${confidence!=null?` · ${confidence}%`:''}`:'Agentic AI listo';
   const ready=!!a?.readyToClose;
   $('#view').innerHTML=`<div class="session">
   <div class="card"><div class="toolbar"><div><h3 style="margin:0">Sesión sobre ${esc(p?.name)}</h3><span class="muted mini">${esc(s.cfg.client)} · ${esc(s.cfg.source)} (${esc(s.cfg.sourceRole||'Sin rol informado')})</span></div><div class="spacer"></div><span class="badge ${s.agent?.status==='error'?'bad':'ok'}">${esc(agentLabel)}</span></div>
   <div class="bar"><div style="width:${timepct}%"></div></div><div class="progressMeta"><span>${mins} / ${s.cfg.duration} min</span><span>${s.transcript.filter(x=>x.who==='client').length} intervenciones cliente</span></div>
   ${s.agent?.error?`<div class="notice" style="margin-top:10px">No se pudo consultar el agente: ${esc(s.agent.error)}. La sesión conserva la transcripción y permite reintentar con la siguiente intervención.</div>`:''}
   <div class="transcript" id="tb">${s.transcript.length?s.transcript.map(x=>`<div class="line ${x.who}"><span class="who">${x.who==='client'?esc(s.cfg.source):x.who==='fac'?esc(s.cfg.fac):'Coach IA'}</span><span class="txt">${esc(x.text)}</span></div>`).join(''):'<div class="empty">Registra las intervenciones relevantes para que el coach Agentic pueda analizarlas.</div>'}</div>
   <div class="toolbar" style="margin-top:10px"><select id="who" class="btn" style="font-weight:500"><option value="client">Cliente</option><option value="fac">Facilitador</option></select><input id="txt" style="flex:1;border:1px solid var(--line);border-radius:9px;padding:9px" placeholder="Escribe una intervención de la conversación…"><button class="btn primary" id="add" ${s.agent?.status==='loading'?'disabled':''}>${s.agent?.status==='loading'?'Analizando…':'Agregar'}</button></div>
   </div>
   <div class="grid" style="gap:12px">
    <div class="card"><div class="listen"><span class="dot"></span>Coach Agentic conectado</div><div class="coverageHead" style="margin-top:14px"><b>Cobertura del feedback</b><strong>${pct}%</strong></div><div class="bar"><div style="width:${pct}%"></div></div><div class="dims">${DIMS.map(d=>`<span class="dim ${s.coverage[d[0]]}">${s.coverage[d[0]]==='complete'?'✓ ':s.coverage[d[0]]==='partial'?'◐ ':'○ '}${d[1]}</span>`).join('')}</div></div>
    ${ready?`<div class="coach"><div class="eyebrow">Cierre recomendado por Agentic AI</div><div class="reason">${esc(q.reason)}</div><div class="question">La sesión ya puede estructurarse para revisión humana.</div></div>`:`<div class="coach"><div class="eyebrow">Siguiente mejor pregunta · ${esc(q.dim)}</div><div class="reason">${esc(q.reason)}</div><div class="question">“${esc(q.question)}”</div><div class="rowActions"><button class="btn agent sm" id="useQ">Usar pregunta</button><button class="btn ghost sm" id="skipQ">Ignorar</button></div></div>`}
    <div class="card"><h3>Hallazgos detectados por el agente</h3><div class="detected">${detectedHTML(s)}</div></div>
    <div class="card"><h3>Métricas de sesión</h3>${metric('sat','Satisfacción',10)}${metric('rec','Recomendación',10)}<div class="notice" style="margin-top:8px">Las métricas cuantitativas permanecen bajo captura/revisión humana y no son inferidas por el agente.</div></div>
    <button class="btn agent" id="finish">⏹ Finalizar y estructurar feedback</button>
   </div></div>`;
   const tb=$('#tb');tb.scrollTop=tb.scrollHeight;
   $('#add').onclick=async()=>{const v=$('#txt').value.trim();if(!v)return;const who=$('#who').value;addLine(who,v);if(who==='client')await sendFeedbackFragment(v);else renderSession()};
   $('#txt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#add').click()}};
   if(!ready){const use=$('#useQ');if(use)use.onclick=()=>{addLine('fac',q.question);renderSession()};const skip=$('#skipQ');if(skip)skip.onclick=()=>{s.qAlt++;renderSession()}}
   ['sat','rec'].forEach(k=>{const el=$('#m_'+k);el.oninput=e=>{s.metrics[k]=+e.target.value;$('#o_'+k).textContent=e.target.value;mark(k==='sat'?'satisfaction':'recommend');renderSession()}});
   $('#finish').onclick=finishSession;
  }
  function metric(k,l,max){const s=state.session,v=s.metrics[k]??Math.ceil(max*.8);return `<div class="metricRow"><span>${l}</span><input id="m_${k}" type="range" min="1" max="${max}" value="${v}"><output id="o_${k}">${s.metrics[k]??'—'}</output></div>`}
  function detectedHTML(s){const a=s.agent?.data;if(a){const out=[];const strengths=Array.isArray(a.strengths)?a.strengths:[];const oms=Array.isArray(a.improvementOpportunities)?a.improvementOpportunities:[];const commitments=Array.isArray(a.commitments)?a.commitments:[];if(strengths.length)out.push(det('⭐ Fortaleza',itemText(strengths.at(-1))));if(oms.length){const om=oms.at(-1);out.push(det('⚠ Oportunidad de mejora',itemText(om.title||om)));if(om&&om.evidence)out.push(det('↳ Evidencia OM',om.evidence))}const impact=evidenceByType(a,'impact');if(impact)out.push(det('↳ Impacto',impact));const challenge=a.suggestedChallenge||(Array.isArray(a.challenges)&&a.challenges.length?itemText(a.challenges.at(-1)):'');if(challenge)out.push(det('🎯 Desafío sugerido',challenge));if(commitments.length)out.push(det('✓ Compromiso',itemText(commitments.at(-1))));if(Array.isArray(a.missingInformation)&&a.missingInformation.length)out.push(det('○ Información pendiente',itemText(a.missingInformation[0])));return out.join('')||'<div class="muted mini">El agente todavía no ha identificado hallazgos estructurados.</div>'}const out=[];if(s.facts.strengths.length)out.push(det('⭐ Fortaleza',s.facts.strengths.at(-1)));if(s.facts.om.length)out.push(det('⚠ Posible OM',s.facts.om.at(-1)));if(s.facts.impact.length)out.push(det('↳ Impacto',s.facts.impact.at(-1)));if(s.facts.challenge.length)out.push(det('🎯 Posible desafío',s.facts.challenge.at(-1)));return out.join('')||'<div class="muted mini">Aún no hay hallazgos estructurados.</div>'}
  function det(t,p){return `<div class="det"><b>${t}</b><p>${esc(p)}</p></div>`}
  function finishSession(){const s=state.session,p=person(s.cfg.personId),pct=covPct();const a=s.agent?.data;if(a&&!a.readyToClose&&!confirm('El agente todavía identifica información pendiente. ¿Deseas generar un borrador para revisión humana de todas formas?'))return;if(!a&&pct<50&&!confirm(`La cobertura es ${pct}%. ¿Deseas finalizar de todas formas?`))return;
   const summary=buildSummary(s,p); s.result={summary};s.closed=true;renderLive()}
  function buildSummary(s,p){const a=s.agent?.data;const last=x=>Array.isArray(x)&&x.length?itemText(x.at(-1)):'No confirmado en la conversación.';if(a){const strengths=Array.isArray(a.strengths)?a.strengths:[];const oms=Array.isArray(a.improvementOpportunities)?a.improvementOpportunities:[];const commitments=Array.isArray(a.commitments)?a.commitments:[];const om=oms.length?oms.at(-1):null;const situation=evidenceByType(a,'situation')||'No confirmado en la conversación.';const behavior=evidenceByType(a,'behavior')||'No confirmado en la conversación.';const impact=evidenceByType(a,'impact')||'No confirmado en la conversación.';const challenge=a.suggestedChallenge||(Array.isArray(a.challenges)&&a.challenges.length?itemText(a.challenges.at(-1)):'No confirmado en la conversación.');const commitment=commitments.length?itemText(commitments.at(-1)):'No confirmado en la conversación.';const omTitle=om?(om.title||itemText(om)):'No se confirmó una oportunidad de mejora.';const executive=`El agente estructuró ${Array.isArray(a.evidence)?a.evidence.length:0} evidencia(s) y ${oms.length} oportunidad(es) de mejora. Estado de la sesión: ${a.phase||'análisis'}${a.readyToClose?' · lista para cierre':''}.`;return {executive,strength:last(strengths),positive:strengths.length?last(strengths):'No confirmado en la conversación.',situation,behavior,impact,frequency:'No confirmado en la conversación.',expectation:commitment!=='No confirmado en la conversación.'?commitment:omTitle,challenge,success:commitment,metricsWhy:last(s.facts.metricsWhy),sat:s.metrics.sat,rec:s.metrics.rec}}const fallback=x=>x.length?x.at(-1):'No confirmado en la conversación.';return {executive:`El cliente reconoce aportes relevantes de ${p.name.split(' ')[0]} y se identificó una oportunidad de desarrollo que debe ser validada antes de enviarse.`,strength:fallback(s.facts.strengths),positive:fallback(s.facts.positive.length?s.facts.positive:s.facts.impact),situation:fallback(s.facts.situation),behavior:fallback(s.facts.behavior),impact:fallback(s.facts.impact),frequency:fallback(s.facts.frequency),expectation:fallback(s.facts.expectation),challenge:fallback(s.facts.challenge),success:fallback(s.facts.success),metricsWhy:fallback(s.facts.metricsWhy),sat:s.metrics.sat,rec:s.metrics.rec}}
  function renderResult(){const s=state.session,r=s.result,p=person(s.cfg.personId);$('#view').innerHTML=`<div class="resultGrid"><div class="card"><div class="toolbar"><div><span class="pill">Borrador estructurado por Agentic AI</span><h3 style="font-size:21px;margin-top:10px">Feedback de ${esc(p.name)}</h3><span class="muted mini">Revisión humana obligatoria antes de enviar.</span></div></div>
   ${box('Resumen ejecutivo','executive',r.executive)}${box('Fortaleza / reconocimiento','strength',r.strength)}${box('Evidencia positiva','positive',r.positive)}
   <h3 style="margin-top:16px">Oportunidad de Mejora · SBI</h3><div class="grid g2">${box('Situación','situation',r.situation)}${box('Comportamiento','behavior',r.behavior)}${box('Impacto','impact',r.impact)}${box('Expectativa','expectation',r.expectation)}</div>
   <h3 style="margin-top:16px">Feed-forward</h3>${box('Desafío sugerido','challenge',r.challenge)}${box('Criterio de éxito','success',r.success)}
   <div class="summaryBox"><h4>Métricas</h4><p>Satisfacción: <b>${r.sat??'—'}/10</b> · Recomendación: <b>${r.rec??'—'}/10</b></p><p>${esc(r.metricsWhy)}</p></div>
   </div><div class="grid" style="align-content:start"><div class="card"><h3>Control de calidad</h3>${qualityRows(s)}<div class="notice" style="margin-top:10px">Hecho ≠ inferencia. El sistema solo debe enviar como afirmación lo que esté respaldado por la conversación.</div></div><div class="card"><h3>Acciones</h3><div class="rowActions"><button class="btn primary" id="saveDraft">Guardar borrador</button><button class="btn agent" id="approve">✓ Aprobar y generar seguimiento</button><button class="btn" id="backLive">Volver a sesión</button></div><p class="muted mini" style="margin-top:10px">“Aprobar” consolida el Feedback, la OM, el Desafío y el Seguimiento. La notificación por correo requiere integración corporativa adicional.</p></div><div class="card"><h3>Vista previa de comunicación</h3><div class="summaryBox mini">Para: ${esc(p.email)}, ${esc(p.advisor)}<br><br><b>Asunto:</b> Resumen de feedback · ${esc(p.name)}<br><br>Hola ${esc(p.name.split(' ')[0])},<br><br>${esc(r.executive)}<br><br><b>Oportunidad principal:</b> ${esc(r.expectation)}<br><br><b>Desafío sugerido:</b> ${esc(r.challenge)}<br><br>Este contenido queda sujeto a revisión de tu Advisor.</div></div></div></div>`;
   $$('textarea[data-r]').forEach(t=>t.oninput=e=>r[e.target.dataset.r]=e.target.value); $('#saveDraft').onclick=()=>alert('Borrador guardado.'); $('#backLive').onclick=()=>{s.closed=false;renderLive()}; $('#approve').onclick=approveSession;}
  function box(title,key,val){return `<div class="summaryBox"><h4>${title}</h4><textarea data-r="${key}" style="width:100%;min-height:70px;border:0;background:transparent;resize:vertical;color:var(--text)">${esc(val)}</textarea></div>`}
  function qualityRows(s){const items=[['Evidencia concreta',s.coverage.situation==='complete'&&s.coverage.behavior==='complete'],['Impacto explícito',s.coverage.impact==='complete'],['OM estructurada',s.coverage.om==='complete'],['Criterio de éxito',s.coverage.success==='complete'],['Métricas + motivo',s.coverage.satisfaction==='complete'&&s.coverage.recommend==='complete'&&s.coverage.metricsWhy==='complete']];return items.map(x=>`<div class="reviewItem"><b>${x[1]?'✓':'○'} ${x[0]}</b><span class="badge ${x[1]?'ok':'warn'}" style="float:right">${x[1]?'Cubierto':'Revisar'}</span></div>`).join('')}
  function approveSession(){const s=state.session,r=s.result,p=person(s.cfg.personId),fid=id('f');db.feedback.push({id:fid,personId:p.id,date:days(0),client:s.cfg.client,source:s.cfg.source,sourceRole:s.cfg.sourceRole,status:'3-Reviewed',sat:r.sat,rec:r.rec,summary:r.executive,approved:true,transcript:s.transcript.slice()});
   let oid=null;if(s.coverage.om==='complete'){oid=id('o');db.oms.push({id:oid,personId:p.id,feedbackId:fid,keyword:(r.expectation||'Oportunidad de desarrollo').slice(0,55),competence:'Por clasificar',situation:r.situation,behavior:r.behavior,impact:r.impact,state:'0-Pendiente'})}
   if(s.coverage.challenge==='complete'){db.challenges.push({id:id('c'),personId:p.id,title:(r.challenge||'Desafío de desarrollo').slice(0,70),criteria:r.success,state:'Ideación',due:days(30),omId:oid,feedbackId:fid})}
   db.meetings.push({id:id('m'),personId:p.id,feedbackId:fid,advisor:p.advisor,date:days(3),done:false});db.audit.push({id:id('a'),at:new Date().toISOString(),action:'Feedback aprobado',feedbackId:fid});persist();s.approved=true;alert('Feedback aprobado. Se crearon el registro, la OM/desafío aplicables y el seguimiento con Advisor.');state.session=null;state.view='feedback';render();}
  function renderFeedback(){const rows=db.feedback.slice().reverse().map(f=>`<tr><td><b>${esc(person(f.personId)?.name)}</b></td><td>${esc(f.client)}</td><td>${esc(f.sourceRole||'—')}<div class="muted mini">${esc(f.source||'')}</div></td><td>${fmt(f.date)}</td><td>${f.sat??'—'}</td><td>${f.rec??'—'}</td><td><span class="badge ${f.approved?'ok':'warn'}">${f.status}</span></td></tr>`).join('');$('#view').innerHTML=`<div class="toolbar"><button class="btn agent" id="newLive">● Nuevo feedback en vivo</button><div class="spacer"></div><span class="pill">${db.feedback.length} registros</span></div><div class="tablewrap"><table><thead><tr><th>Talento</th><th>Cliente</th><th>Fuente</th><th>Fecha</th><th>Satisf.</th><th>Recom.</th><th>Estado</th></tr></thead><tbody>${rows||'<tr><td colspan=7>Sin registros</td></tr>'}</tbody></table></div>`;$('#newLive').onclick=()=>{state.view='live';render()}}
  function renderOM(){const rows=db.oms.map(o=>`<tr><td><b>${esc(person(o.personId)?.name)}</b></td><td>${esc(o.keyword)}</td><td>${esc(o.competence)}</td><td><b>S:</b> ${esc(o.situation)}<br><b>B:</b> ${esc(o.behavior)}<br><b>I:</b> ${esc(o.impact)}</td><td><span class="badge agentb">${esc(o.state)}</span></td></tr>`).join('');$('#view').innerHTML=`<div class="tablewrap"><table><thead><tr><th>Talento</th><th>OM</th><th>Competencia</th><th>SBI</th><th>Maduración</th></tr></thead><tbody>${rows||'<tr><td colspan=5>Sin oportunidades de mejora registradas.</td></tr>'}</tbody></table></div>`}
  function renderChallenges(){const groups=['Ideación','Por hacer','En progreso','Hecho'];$('#view').innerHTML=`<div class="kanban">${groups.map(g=>`<div class="col"><h4>${g}</h4>${db.challenges.filter(c=>c.state===g).map(c=>`<div class="task"><strong>${esc(c.title)}</strong><p>${esc(person(c.personId)?.name)}</p><p>Éxito: ${esc(c.criteria)}</p><p>Vence: ${fmt(c.due)}</p></div>`).join('')||'<div class="muted mini">Sin desafíos</div>'}</div>`).join('')}</div>`}
  function renderFollow(){const rows=db.meetings.map(m=>`<tr><td><b>${esc(person(m.personId)?.name)}</b></td><td>${esc(m.advisor)}</td><td>${fmt(m.date)}</td><td><span class="badge ${m.done?'ok':'warn'}">${m.done?'Realizada':'Pendiente'}</span></td><td><button class="btn sm" data-done="${m.id}">${m.done?'Reabrir':'Marcar realizada'}</button></td></tr>`).join('');$('#view').innerHTML=`<div class="tablewrap"><table><thead><tr><th>Colaborador</th><th>Advisor</th><th>Fecha</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${rows||'<tr><td colspan=5>Sin seguimientos</td></tr>'}</tbody></table></div>`;$$('[data-done]').forEach(b=>b.onclick=()=>{const m=db.meetings.find(x=>x.id==b.dataset.done);m.done=!m.done;persist();renderFollow()})}
  function renderPeople(){
   const rows=db.people.map(p=>`<tr><td><b>${esc(p.name)}</b><div class="muted mini">${esc(p.email||'')}</div></td><td>${esc(p.client||'—')}</td><td>${esc(p.unit||'—')}</td><td>${esc(p.squad||'—')}</td><td>${esc(p.advisor||'—')}</td><td><span class="badge ok">${esc(p.status)}</span></td></tr>`).join('');
   $('#view').innerHTML=`<div class="card" style="margin-bottom:16px"><h3>Agregar persona</h3><div class="formgrid"><label class="field"><span>Nombre completo *</span><input id="pn"></label><label class="field"><span>Correo</span><input id="pe" type="email"></label><label class="field"><span>Cliente</span><input id="pc"></label><label class="field"><span>Unidad</span><input id="pu"></label><label class="field"><span>Squad / Equipo</span><input id="ps"></label><label class="field"><span>Advisor *</span><input id="pa"></label></div><button class="btn agent" id="addPerson" style="margin-top:14px">+ Agregar al directorio</button></div><div class="toolbar"><b>Directorio</b><div class="spacer"></div><span class="pill">${db.people.length} personas</span></div><div class="tablewrap"><table><thead><tr><th>Persona</th><th>Cliente</th><th>Unidad</th><th>Squad</th><th>Advisor</th><th>Estado</th></tr></thead><tbody>${rows||'<tr><td colspan=6>El directorio está vacío.</td></tr>'}</tbody></table></div>`;
   $('#addPerson').onclick=()=>{const name=$('#pn').value.trim(),advisor=$('#pa').value.trim();if(!name||!advisor){alert('Nombre y Advisor son obligatorios.');return}db.people.push({id:id('p'),name,email:$('#pe').value.trim(),client:$('#pc').value.trim(),unit:$('#pu').value.trim(),squad:$('#ps').value.trim(),advisor,status:'Activo'});persist();renderPeople()};
  }
  function renderSettings(){
   $('#view').innerHTML=`<div class="grid g2"><div class="card"><h3>Parámetros del Coach</h3><div class="formgrid"><label class="field"><span>Duración objetivo</span><input id="cfgDur" type="number" value="${db.config.sessionMinutes}"></label><label class="field"><span>Cobertura objetivo (%)</span><input id="cfgCov" type="number" value="${db.config.coverageTarget}"></label><label class="field"><span>Escala satisfacción/recomendación</span><select id="cfgScale"><option ${db.config.metricScale===10?'selected':''}>10</option><option ${db.config.metricScale===5?'selected':''}>5</option></select></label><label class="field"><span>Canal de preguntas</span><select id="cfgMode"><option value="private" ${db.config.questionMode==='private'?'selected':''}>Panel privado</option><option value="chat" ${db.config.questionMode==='chat'?'selected':''}>Chat de reunión</option></select></label></div><button class="btn primary" id="saveCfg" style="margin-top:14px">Guardar configuración</button></div><div class="card"><h3>Gobierno</h3><div class="reviewItem"><b>Revisión humana</b><div class="muted mini">Obligatoria antes de consolidar el feedback.</div></div><div class="reviewItem"><b>Trazabilidad</b><div class="muted mini">Feedback, OM, Desafío y Seguimiento mantienen relación por identificador.</div></div><div class="reviewItem"><b>Acceso</b><div class="muted mini">La disponibilidad de la app se administra mediante las políticas y grupos de Microsoft Teams.</div></div><div class="reviewItem"><b>Persistencia</b><div class="muted mini">La interfaz usa almacenamiento local para los registros de UI. El análisis en vivo consume el agente corporativo en aXet Cloud; la persistencia multiusuario compartida todavía requiere un repositorio corporativo.</div></div></div><div class="card"><h3>Respaldo de datos</h3><p class="muted mini">Exporta un respaldo antes de limpiar o cambiar de dispositivo.</p><div class="rowActions"><button class="btn" id="exportData">Exportar JSON</button><label class="btn" for="importData" style="cursor:pointer">Importar JSON</label><input id="importData" type="file" accept="application/json" class="hidden"><button class="btn danger" id="clearData">Borrar datos locales</button></div></div><div class="card"><h3>Integraciones corporativas</h3><div class="reviewItem"><b>Microsoft Teams</b><div class="muted mini">Disponible en personal, canal, chat grupal y contextos de reunión.</div></div><div class="reviewItem"><b>aXet Agentic AI</b><div class="muted mini">Conectado al endpoint Cloud del Feedback Coach para análisis de fragmentos, evidencia y Next Best Question.</div></div><div class="reviewItem"><b>Transcripción automática</b><div class="muted mini">Requiere Microsoft Graph Transcript API habilitada por el administrador y un backend/identidad de aplicación.</div></div><div class="reviewItem"><b>Persistencia multiusuario</b><div class="muted mini">Requiere base de datos o repositorio corporativo con autenticación y RBAC.</div></div></div></div>`;
   $('#saveCfg').onclick=()=>{db.config.sessionMinutes=+$('#cfgDur').value;db.config.coverageTarget=+$('#cfgCov').value;db.config.metricScale=+$('#cfgScale').value;db.config.questionMode=$('#cfgMode').value;persist();alert('Configuración guardada')};
   $('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='feedback-coach-ai-backup-'+days(0)+'.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)};
   $('#importData').onchange=e=>{const file=e.target.files&&e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const imported=JSON.parse(r.result);if(!imported||!Array.isArray(imported.people)||!imported.config)throw new Error('Formato inválido');if(confirm('¿Reemplazar los datos actuales por el respaldo seleccionado?')){db=imported;persist();state.session=null;renderSettings()}}catch(err){alert('El archivo no corresponde a un respaldo válido de Feedback Coach AI.')}};r.readAsText(file)};
   $('#clearData').onclick=()=>{if(confirm('¿Borrar todos los datos almacenados en este navegador? Esta acción no se puede deshacer.')){db=seed();persist();state.session=null;renderSettings()}};
  }
  render();
  if (window.__teamsReady && typeof window.__teamsReady.then === 'function') {
    window.__teamsReady.then(function(ctx){
      try {
        const fc = ctx && ctx.page && ctx.page.frameContext;
        if (fc === 'meetingSidePanel' && !state.session) {
          state.view = 'live';
          if (options && options.frameContext === 'meetingSidePanel' && !state.session) { state.view = 'live'; }
  render();
        }
      } catch(e) { console.warn('Teams context adaptation failed', e); }
    });
  }
}

